platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings! 

target 'NYTMostPopular' do
 

pod 'Alamofire'      
pod 'SDWebImage' 

 
  target 'NYTMostPopularTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTMostPopularUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
